site_name: Lista de Exerc√≠cios
site_url: https://exercicios.dunossauro.com/
repo_url: https://github.com/dunossauro/exercicios-python-brasil
repo_name: dunossauro/exercicios-python-brasil

theme:
  name: material
  custom_dir: overrides
  palette:
    - scheme: slate
      primary: black
      toggle:
        icon: material/weather-sunny
        name: Modo claro
    - scheme: default
      primary: black
      toggle:
        icon: material/weather-night
        name: Modo noturno

plugins:
  - search
  - markdown-exec
  - git-authors:
      show_email_address: false
      show_line_count: true
  - git-revision-date-localized

markdown_extensions:
- attr_list
- pymdownx.superfences
- pymdownx.inlinehilite
- pymdownx.tabbed:
    alternate_style: true

extra_javascript:
  - assets/javascripts/pyodide.js
  - assets/javascripts/fonts.js

fonts:
  icon: material/format-font
  preferences:
    - text: Default
    - text: OpenDyslexic
      code: OpenDyslexicMono
      src: https://fonts.cdnfonts.com/css/opendyslexic
